import assert from 'node:assert/strict';
import { readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { documentFixture, specText } from '../tests/fixtures/document-updates.mjs';
import { pathToFileURL } from 'node:url';
const appRoot = resolve(process.env.IPS_TEST_APP_ROOT || resolve(import.meta.dirname, '..'));
const { startStudio } = await import(pathToFileURL(join(appRoot, 'src/server.mjs')).href);
import { makeReadOnlyReviewConfig } from '../src/review-package.mjs';
import { launchHeadlessBrowser } from './browser-runtime.mjs';

const f = await documentFixture();
await writeFile(join(f.directory, 'layout.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64'));
const source = `# 全文测试\n\n## 公共使用要求\n大字号下确认取消可触达。\n\n![功能线框](./layout.png)\n\n${specText}\n## 工程实现约束\n重试复用操作标识。\n`;
await writeFile(f.sourceSpecPath, source);
const studio = await startStudio({ appRoot, host: '127.0.0.1', port: 0, statePath: join(f.directory, 'state/projects.json') });
const browser = await launchHeadlessBrowser();
try {
  const response = await fetch(`${studio.url}api/project/confirm`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(f.project) });
  assert.equal(response.status, 200);
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  page.setDefaultTimeout(12000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(studio.url);
  const frameInput = page.frameLocator('iframe').getByRole('textbox', { name: '保留画布输入' });
  await frameInput.fill('继续原任务');
  await page.getByRole('button', { name: /任务板 页面/ }).click();
  await page.getByText('保存任务', { exact: true }).first().click();
  await page.getByRole('tab', { name: '操作定义' }).click();
  await page.getByRole('button', { name: '编辑完整节点' }).click();
  await page.getByLabel('节点标题', { exact: true }).fill('未保存标题');
  const open = () => page.getByRole('button', { name: '完整 Spec', exact: true }).click();
  const reader = page.getByRole('dialog', { name: '完整 Spec', exact: true });
  await open();
  await reader.getByText('大字号下确认取消可触达。', { exact: true }).waitFor();
  assert.equal(await reader.getByRole('img', { name: '功能线框', exact: true }).evaluate(el => el.complete && el.naturalWidth > 0), true);
  await reader.getByLabel('Spec 章节').selectOption({ label: '工程实现约束' });
  await reader.getByText('重试复用操作标识。', { exact: true }).waitFor();
  assert.ok(await reader.getByTestId('full-spec-body').evaluate(element => element.scrollTop > 0));
  await reader.getByRole('button', { name: 'Close', exact: true }).click();
  assert.equal(await page.getByLabel('节点标题', { exact: true }).inputValue(), '未保存标题');
  assert.equal(await frameInput.inputValue(), '继续原任务');
  await page.getByRole('button', { name: '保存到原文件', exact: true }).click();
  await open();
  await reader.getByRole('heading', { name: /ACTION.*TASK-SAVE.*未保存标题/ }).waitFor();
  const savedSource = await readFile(f.sourceSpecPath, 'utf8');
  await writeFile(f.sourceSpecPath, savedSource.replace('重试复用操作标识。', '新的工程约束：保留原操作标识。'));
  await reader.getByRole('button', { name: '加载新版', exact: true }).click();
  await reader.getByText('新的工程约束：保留原操作标识。', { exact: true }).waitFor();
  assert.equal(await frameInput.inputValue(), '继续原任务');
  await page.setViewportSize({ width: 420, height: 850 });
  const bounds = await reader.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.width <= 421);
  await reader.getByLabel('Spec 章节').selectOption({ label: '公共使用要求' });
  await reader.getByText('大字号下确认取消可触达。', { exact: true }).waitFor();
  await page.screenshot({ path: 'output/playwright/full-spec-reading.png' });
  // 评审包使用同一冻结配置，验证其既有只读模式能阅读全文及草稿说明。
  const current = await (await fetch(`${studio.url}api/config`)).json();
  current.specDocument.pendingDraft = true;
  const frozen = makeReadOnlyReviewConfig(current, 'index.html', 'now');
  await page.route('**/api/config', route => route.fulfill({ json: frozen }));
  await page.reload();
  await open();
  await reader.getByText(/节点修订草稿尚未写回/).waitFor();
  assert.equal(await reader.getByRole('img', { name: '功能线框', exact: true }).evaluate(el => el.complete && el.naturalWidth > 0), true);
  await reader.getByLabel('Spec 章节').selectOption({ label: '工程实现约束' });
  await reader.getByText('新的工程约束：保留原操作标识。', { exact: true }).waitFor();
  frozen.specDocument = null;
  await page.reload();
  assert.equal(await page.getByRole('button', { name: '完整 Spec', exact: true }).isDisabled(), true);
  assert.deepEqual(errors, []);
  console.log('完整 Spec 阅读通过：节点外全文、章节定位、编辑恢复、保存与刷新、窄屏、冻结配置和缺来源。');
} finally {
  await browser.close(); await studio.stop(); await rm(f.directory, { recursive: true, force: true });
}
