import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { startWorkbench } from '../src/server.mjs';
import { createEmptySpecMap } from '../src/contracts.mjs';
import { launchHeadlessBrowser } from './browser-runtime.mjs';
const root=resolve(import.meta.dirname,'..');
const temp=await mkdtemp(join(tmpdir(),'ips-batch-'));
const htmlPath=join(temp,'index.html'), specPath=join(temp,'product.spec.json'), mapPath=join(temp,'spec-map.json');
await writeFile(htmlPath,'<!doctype html><title>任务看板</title><main><h1>任务看板</h1><button id="reliable">可靠操作</button><button id="shared">竞争操作</button><button id="taken">已有操作</button><button id="amb1">歧义操作</button><button id="amb2">歧义操作</button></main>');
const bundle=JSON.parse(await readFile(resolve(root,'examples/task-board/product.spec.json'),'utf8'));
const node=(id,title)=>({id,type:'ACTION',title,pageId:'TASK-PAGE-BOARD',status:'draft',sourceKind:'product-decision',anchorHints:[title],contentBlocks:[],relations:[]});
bundle.pages[0].routeHints=['/target/index.html'];
bundle.modules=[{...bundle.modules[0],nodes:[node('RELIABLE','可靠操作'),node('SHARED-A','竞争操作'),node('SHARED-B','竞争操作'),node('TAKEN','已有操作'),node('TAKEN-SECOND','已有操作的另一份说明'),node('CONFLICT','已有操作'),node('AMBIGUOUS','歧义操作'),node('LOW','完全无对应项')]}];
await writeFile(specPath,JSON.stringify(bundle));
const map=createEmptySpecMap(bundle.product.id,htmlPath);
const existing={id:'urn:test:taken',type:'Annotation',motivation:'linking',body:{id:'TAKEN',type:'Text'},target:{source:htmlPath,context:{url:'/target/index.html'},selector:{type:'CssSelector',value:'#taken'},fingerprint:{tag:'button',text:'已有操作'}},status:'confirmed'};
const second={...structuredClone(existing),id:"urn:test:taken-second",body:{id:"TAKEN-SECOND",type:"Text"}};
map.items.push(existing,second);await writeFile(mapPath,JSON.stringify(map));
const studio=await startWorkbench({appRoot:root,statePath:join(temp,'state.json'),mode:'map',htmlPath,specPath,mapPath,host:'127.0.0.1',port:0});
const browser=await launchHeadlessBrowser();
try {
 const page=await browser.newPage({viewport:{width:1625,height:870}});
 await page.goto(studio.url,{waitUntil:'networkidle'});
 const button=page.getByTestId('one-click-bind');
 await button.getByText('一键绑定 · 1 项').waitFor();
 const marker=page.frameLocator('iframe').locator('#ips-overlay-host button.marker').filter({hasText:'2'});
 await marker.waitFor();
 assert.equal(await marker.locator('.marker-count').innerText(),'2');
 await marker.click();
 await page.getByRole('button',{name:/已有操作的另一份说明 TAKEN-SECOND/}).click();
 await page.getByRole('heading',{name:'已有操作的另一份说明',exact:true}).waitFor();
 let failSave=true;
 await page.route('**/api/map', async route => {
   if (failSave && route.request().method()==='POST') await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'模拟保存失败'})});
   else await route.continue();
 });
 await button.click();
 await page.getByTestId('map-save-status').filter({hasText:'保存失败'}).waitFor();
 assert.equal(JSON.parse(await readFile(mapPath,'utf8')).items.length,2,'失败不能声称落盘');
 failSave=false;
 await page.getByTestId('map-save-status').click();
 await page.getByTestId('map-save-status').filter({hasText:'已自动保存'}).waitFor();
 // Wait for disk state rather than treating local UI binding as persistence.
 await page.waitForFunction(async()=>{const r=await fetch('/api/config');const c=await r.json();return c.specMap.items.some(i=>i.body.id==='RELIABLE')});
 const saved=JSON.parse(await readFile(mapPath,'utf8'));
 assert.deepEqual(saved.items.map(i=>i.body.id).sort(),['RELIABLE','TAKEN','TAKEN-SECOND']);
 assert.deepEqual(saved.items.find(i=>i.body.id==='TAKEN'),existing);
 assert.equal(await button.isDisabled(),true);
 await page.reload({waitUntil:'networkidle'});
 assert.equal(await button.isDisabled(),true);
 await page.getByRole('tab',{name:'评审模式',exact:true}).click();
 assert.equal(await button.count(),0);
 const floating=page.getByTestId('spec-overview-float');
 assert.equal(Math.round((await floating.boundingBox()).width),360);
 assert.equal(Math.round((await floating.boundingBox()).height),await floating.evaluate(el => el.parentElement.clientHeight - 24));
 await page.getByRole('button',{name:'拖动 Spec 总览'}).press('ArrowDown');
 await marker.click();
 await page.getByRole('button',{name:/已有操作的另一份说明 TAKEN-SECOND/}).click();
 await page.getByRole('heading',{name:'已有操作的另一份说明',exact:true}).waitFor();
 assert.equal(await floating.isVisible(),true,'选择双 Spec 圆点后总览保持可见');
 await page.setViewportSize({width:1100,height:870});
 assert.equal(await floating.isVisible(),true,'窄窗口打开详情不隐藏总览');
 console.log('一键绑定通过：可靠项保存并刷新保留；竞争、已有目标冲突、歧义、低关联跳过；已有绑定不变；只读无入口');
} finally {await browser.close();await studio.stop();}
