import assert from 'node:assert/strict';
import { mkdtemp, realpath, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createPrdReviewMcp } from '../src/prd-review-mcp.mjs';
import { readPrdDocument } from '../src/prd-service.mjs';
import { source } from '../tests/fixtures/prd-review.mjs';
import { launchHeadlessBrowser } from './browser-runtime.mjs';

const projectPath = await realpath(await mkdtemp(join(tmpdir(), 'ips-prd-entry-browser-')));
const prdPath = join(projectPath, 'PRD.md');
const statePath = join(projectPath, '.state/projects.json');
await writeFile(prdPath, source);
let prompts = 0;
let manager = createPrdReviewMcp({ statePath, elicit: async () => { prompts++; return { action: 'accept', content: { review: '稍后评审' } }; } });
const browser = await launchHeadlessBrowser();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  const input = { projectPath, prdPath };
  const deferred = await manager.call('request_prd_review', input);
  assert.equal(deferred.status, 'deferred');
  assert.equal(deferred.url, undefined);
  await manager.close();
  manager = createPrdReviewMcp({ statePath, elicit: () => assert.fail('reconnect must not prompt again') });
  assert.equal((await manager.call('request_prd_review', input)).status, 'deferred');
  const opened = await manager.call(deferred.resume.tool, deferred.resume.arguments);
  await page.goto(opened.url);
  await page.getByTestId('prd-review-panel').waitFor();
  await page.getByTestId('prd-document').getByText('帮助团队管理任务。', { exact: true }).waitFor();
  const drawer = page.locator('[data-slot="sheet-content"]').filter({ has: page.getByTestId('prd-review-panel') });
  assert.equal(Math.round((await drawer.boundingBox()).width), 1280);
  assert.equal(await page.locator('iframe').count(), 0, 'no fake HTML canvas');
  await page.getByRole('button', { name: '关闭 PRD', exact: true }).click();
  await page.getByRole('button', { name: '打开 PRD', exact: true }).click();
  const inputBox = page.getByPlaceholder('补充整批说明（可选）…');
  await inputBox.fill('请补充任务说明');
  await page.reload();
  await inputBox.waitFor();
  assert.equal(await inputBox.inputValue(), '请补充任务说明');
  await page.getByRole('button', { name: '发送给原 Codex 任务', exact: true }).click();
  const batch = await manager.call('wait_prd_feedback', { sessionId: opened.sessionId, timeoutMs: 5000 });
  assert.equal(batch.status, 'submitted');
  const revised = source.replace('帮助团队管理任务。', '帮助团队创建和管理任务。');
  await writeFile(prdPath, revised);
  await manager.call('publish_prd_revision', { sessionId: opened.sessionId, batchId: batch.batch.id, revision: (await readPrdDocument(prdPath)).document.revision, summary: '已补充任务目标。' });
  await page.getByTestId('prd-document').getByText('帮助团队创建和管理任务。', { exact: true }).waitFor();
  assert.equal(prompts, 1);
  await page.getByRole('button', { name: '确认当前版本', exact: true }).click();
  const confirmation = await manager.call('wait_prd_feedback', { sessionId: opened.sessionId, timeoutMs: 5000 });
  assert.equal(confirmation.status, 'confirmation_requested');
  assert.equal(await readFile(prdPath, 'utf8'), revised, 'confirmation button does not write PRD');
  await writeFile(prdPath, revised.replace('文档状态：草稿', '文档状态：已确认'));
  await manager.call('complete_prd_confirmation', { sessionId: opened.sessionId, sourceRevision: confirmation.revision, confirmedPrdPath: prdPath, revision: (await readPrdDocument(prdPath)).document.revision, summary: '测试模拟正式确认。' });
  await page.getByText('当前版本已确认', { exact: true }).waitFor();
  await page.setViewportSize({ width: 420, height: 850 });
  await page.screenshot({ path: '/tmp/ips-prd-entry-narrow.png' });
  assert.equal(Math.round((await drawer.boundingBox()).width), 420);
  assert.deepEqual(errors, []);
  console.log('生成后稍后评审、重连、原入口继续、无 HTML 全文阅读、刷新草稿、修订和确认浏览器闭环通过。');
} finally {
  await browser.close();
  await manager.close();
  await rm(projectPath, { recursive: true, force: true });
}
